name: CI - Build and Upload Artifacts

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.25.2"

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.20.0"

            - name: Run make
              working-directory: ${{ github.workspace }}
              run: |
                  go mod download
                  cd frontend
                  npm i
                  cd ..
                  make all frontend

            - name: Upload Go binaries
              if: success()
              uses: actions/upload-artifact@v4
              with:
                  name: binaries
                  path: |
                      monitor-agent
                      monitor-server

            - name: Upload frontend build
              if: success()
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-build
                  path: frontend/build
